### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by FallenHero66** [oshosanya/graphql-export#22]
Hi! I'm trying to use this tool to export a GraphQL schema to Insomnia, and it fails with the following stack trace:

> Argument query-name was not supplied. Using default value:  RootQueryType 
Argument mutation-name was not supplied. Using default value:  RootMutationType 
(node:16876) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/graphql-export/dist/exporters/index.js:73:121)
    at step (/usr/local/share/.config/yarn/global/node_modules/graphql-export/dist/exporters/index.js:33:23)
    at Object.throw (/usr/local/share/.config/yarn/global/node_modules/graphql-export/dist/exporters/index.js:14:53)
    at rejected (/usr/local/share/.config/yarn/global/node_modules/graphql-export/dist/exporters/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:16876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Maybe it is important to note, that the schema returned is huge (the introspection response is 1.3mb big, GraphQL Voyager gets hung up when trying to import it).

Sadly, I cannot give any detailed information on the schema where this is thrown, as it is from a project at work... But maybe this error already helps you in in finding the cause!

Best,
F

**Comment by FallenHero66** [comment]
Closed because simply typo in URL....
